name: Android CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        android-version: [35]

    steps: [ { name: "Checkout code", uses: actions/checkout@v2 }, { name: "Set up JDK 11" } ]
